# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bowlinggame',
            name='Result',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bowlinggame',
            name='StrikeSpare',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bowlinggame',
            name='Time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
