# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20171011_0724'),
    ]

    operations = [
        migrations.AddField(
            model_name='bowlinggame',
            name='StrikeSpareInfo',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
